PATH_OPTIMIZER = "path_opt"
WEIGHT_OPTIMIZER = "w_opt"

PATHS_FROM_FILE = "file"
PATHS_FROM_FLOW = "flow"
PATHS_FROM_K_SHORTEST_PATHS = "ksp"
PATHS_FROM_K_WEIGHTED_SHORTEST_PATHS = "w_ksp"
PATHS_FROM_SHORTEST_PATHS = "sp"
